### ISSUE TITLE
Animation based on isActive prop doesn't complete

### ISSUE THREAD

**Issue by Arrow7000** [computerjazz/react-native-draggable-flatlist#121]
I have a list of cards that I am reordering. I want each card to have a little animation based on whether it `isActive`.

I want the active card's size to increase slightly when the item is active so it looks like it's being lifted up. The growing animation works fine, but the shrinking animation when `isActive === false` again doesn't complete for some reason. I'm guessing that's because the list rerenders as soon as the item gets back into place, cancelling any animations still in progress.

I made a snack that reproduces the issue: https://snack.expo.io/@aronadler/0633b6

You can see that when the item starts to be dragged the card smoothly grows in size. The start animation works. But when it gets released the card snaps back to its original size immediately. Ideally the animation would complete and the card smoothly animate back to its original size.

**Comment by computerjazz** [comment]
`isActive` is true until the item is finished animating into place. You'll need to kick off your scale-down animation via the `onRelease` callback in order to animate your component immediately on gesture release.

I've actually already built this functionality out in a gist which may be helpful: https://gist.github.com/computerjazz/1df4a146bdb260882f52d8d565fd3558#file-drag-with-scale-effect-tsx

**Comment by computerjazz** [comment]
Here's where you'd configure your scale amount -- this animation is configured to scale up to 1.1x when active https://gist.github.com/computerjazz/1df4a146bdb260882f52d8d565fd3558#file-drag-with-scale-effect-tsx-L115
