### ISSUE TITLE
`index` is undefined in `renderItem` calls until the 11th item

### ISSUE THREAD

**Issue by kdo1234** [computerjazz/react-native-draggable-flatlist#128]
`index` is undefined in `renderItem` calls until the 11th item.
Here is a snack that reproduces the issue.
https://snack.expo.io/S176xY7ZU

**Comment by curiousdustin** [comment]
I also had a similar issue. I fixed my use case by adding this to my fork:
https://github.com/curiousdustin/react-native-draggable-flatlist/commit/8be6e0012276e784b11ddc26919872316e35f2ac

I think there are cases where the `data` prop can change without triggering a re-render of all the items. So in my case, `data` was starting out as and empty array `[]`, and later changing to an array of items. In this case, `keyToIndex` was not getting set until AFTER the new items had rendered the first time.

Also related to #104

**Comment by curiousdustin** [comment]
@computerjazz , has this been addressed by any of the recent changes?

Does my hacky fix lead you to a better idea to safeguard this?

**Comment by curiousdustin** [comment]
@computerjazz, sorry to keep buggin' about this one, but it seems to still be happening. 

As mentioned above, I have a fix, but I feel like there is probably a better way.

**Comment by computerjazz** [comment]
Added a fallback index setter in `2.3.2`, let me know if this solves the issue: https://github.com/computerjazz/react-native-draggable-flatlist/blob/master/src/index.tsx#L793

I'm hesitant to re-render all rows when index changes, as that could cause perf issues if I drag an item from the top to the bottom of a list. Because of this, `index` can't be 100% trusted to be up-to-date, which is a bummer. I'm considering adding a `getIndex()` method to `renderItem` instead, so when you _need_ the index, you can manually get it, but a changing index won't be the trigger of a re-render. Thoughts?

**Comment by computerjazz** [comment]
Also, have either of you noticed that Snacks are broken recently? I have to use `expo 34` or else I get an error on `reanimated` import...

**Comment by kdo1234** [comment]
Hi, I haven't tried the patch yet. To me it seems to make sense to rerender all visible rows when the drag completes, because that is what FlatList would do if a row was inserted or removed. Thank you

**Comment by curiousdustin** [comment]
I also can't try this update until next month. 

And, I don't regularly use Snacks, sorry, no info there either...

**Comment by computerjazz** [comment]
fixed in https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v2.3.2

Please open a new issue if still seeing this behavior

**Comment by tara-singh-danu** [comment]
```
Use getIndex()
Like
const renderItem = ({
    item,
    getIndex,
    drag,
    isActive,
  }: RenderItemParams<>) => {
console.log("index",getIndex())
return(
.....
)
}
```
