### ISSUE TITLE
Row doesn't deactivate on touch release in iOS

### ISSUE THREAD

**Issue by Peretz30** [computerjazz/react-native-draggable-flatlist#151]
![](https://im5.ezgif.com/tmp/ezgif-5-811e4ebe45f3.gif)

**Describe the bug**
I use this gist:
https://gist.github.com/computerjazz/1df4a146bdb260882f52d8d565fd3558#file-drag-with-scale-effect-tsx

On iOS 13.3 device and emulator if you trying to touch row, not moving and then release your touch, after that row is still activated. Works fine on Android. 

**To Reproduce**
Run gist

**Platform & Dependencies**
 - Platform: iOS 13.3
 - React Native or Expo version: "react-native": "0.60.5",
 - Reanimated version:  "react-native-reanimated": "^1.2.0",
 - React Native Gesture Handler version:  "react-native-gesture-handler": "^1.4.1",

**Comment by computerjazz** [comment]
Looks like you're on v1, that gist only applies to v2.x

**Comment by computerjazz** [comment]
ah missed the part about not moving. yep that's a bug -- `onRelease` isn't being called in that case.

**Comment by Peretz30** [comment]
@computerjazz yes, its on v2 version. Thanks for response. Can you, please, say how much time you need to publish a fix?

**Comment by computerjazz** [comment]
Should be fixed in `2.3.1`

**Comment by Peretz30** [comment]
@computerjazz wow! Works perfect! Thanks man!

**Comment by amazingmarvin** [comment]
I also ran into this bug.  The workaround I'm using to prevent related crashes and weird behavior is:

```
  // this.draggableFlatlist is a ref to my DraggableFlatlist component
  this.draggableFlatlist.disabled.setValue(1);
  this.draggableFlatlist.resetHoverState();
```

which I call whenever the user does another action with the list, like a regular press or editing the title of an item.  I did a bit of digging before I found this bug report and found out that `react-native-gesture-handler` doesn't provide an imperative means to cancel the animation.  So toggling disabled seems to be the way to go.  But maybe you have a better way to accomplish this anyway!  I feared that the bug was caused by the `activationDistance={15}` I have in order to make swiping and tapping work, but my testing shows it happens with or without this prop.

Looking forward to 2.3.1!
