### ISSUE TITLE
Scroll compatibility with ViewPager is lost when upgrading draggable-flatlist from 1.1.9 to 2.3.1

### ISSUE THREAD

**Issue by let-aurn** [computerjazz/react-native-draggable-flatlist#161]
**Describe the bug**

Scroll compatibility with [`@react-native-community/viewpager`](https://github.com/react-native-community/react-native-viewpager) is lost when upgrading `react-native-draggable-flatlist` from `1.1.9` to `2.3.1`.

The issue:
I cannot swipe the ViewPager right/left when touching the `DraggableFlatList` element.
Swiping outside `DraggableFlatList` works fine though.
And with the exact same config/style, it works perfectly with the version 1.1.9.

**To Reproduce**

```jsx
<ViewPager>
  <View>
        <Lorem />
  </View>
  <View>
        <DraggableFlatList ... />
  </View>
  <View>
        <Ipsum />
  </View>
</ViewPager>
```

**Platform & Dependencies**

Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: Android (not tested on iOS)
 - React Native or Expo version: Native
 - Reanimated version: 1.7.0
 - React Native Gesture Handler version: 1.6.0

**Comment by computerjazz** [comment]
did you try adding an `activationDIstance` prop?
https://github.com/computerjazz/react-native-draggable-flatlist#props
This is the distance a finger must travel before the gesture handler activates. It was added so that the list doesn't capture tab swipe gestures, and I would guess it may solve this issue.
It may require some experimentation to find the right number, I'd start at around `30` and go from there.

**Comment by let-aurn** [comment]
Cool. Setting `activationDistance ` to `30` is a good works well. Thank you.
