### ISSUE TITLE
Drag and Drop not working on iOS but working for Android

### ISSUE THREAD

**Issue by leminhcse** [computerjazz/react-native-draggable-flatlist#477]
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**
Dragging does not work as expected on iOS but work well on Android (I am using iOS 13.7 and 14.6).

**To Reproduce**
Please see the attached video.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - react-native-draggable-flatlist version: 3.1.2
 - Platform: iOS, Android
 - React Native or Expo version: 0.69.5
 - Reanimated version: 2.2.4
 - React Native Gesture Handler version: 1.6.1

**Additional context**
```
    <DraggableFlatList
      style={[styles.container(design.padding, design.backgroundHEX)]}
      containerStyle={{ flex : 1 }}
      scrollEnabled={true}
      data={data}
      renderItem={renderItem}
      keyExtractor={(item, index) => `draggable-item-${index}`}
      onDragEnd={e=>{
        onDragEnd(e);
        triggerHapticFeedback();
      }}
      onDragBegin={() => triggerHapticFeedback()}
      ListFooterComponent={listFooterComponent}
  />

```

https://github.com/computerjazz/react-native-draggable-flatlist/assets/45330126/57c2e6c0-e759-41b3-8853-1c91930d4ba7

https://github.com/computerjazz/react-native-draggable-flatlist/assets/45330126/c52a3861-0d3f-4ce8-abfd-745b5500c54e

**Comment by VadzimAlkhimionak** [comment]
the same issue

**Comment by jcarioti** [comment]
Just noticed the same issue in our app as well. Seems to be affecting both the drag & drop functionality as well as the "swipeable-item" integration. Works fine in Android, but barely working support for drag&drop or horizontal swiping on iOS.

react-native-draggable-flatlist version: 4.0.1
Platform: iOS
React Native: 0.72.0
Reanimated version: 3.3.0
React Native Gesture Handler version: 2.12.0

**Comment by leminhcse** [comment]
Hi there ! This has been fixed, Thanks !

**Comment by sentry0** [comment]
I just tested iOS using the iPhone Pro Max Simulator, and it's definitely hanky for me.  I don't know at this point if it's because it's in the Simulator or if it will affect an actual device.

Basically, it seemed very hit-and-miss in terms of detecting a scroll or detecting a drag event.  Most of the time the drag event would look like it fired but nothing was draggable.  Except when it was ¯\_(ツ)_/¯

I'm a little concerned and I have no access to an iOS device.

Does anyone want to help me out and join the alpha test for my app on a real iOS device???

**Comment by sentry0** [comment]
Okay, so I figured out a workaround that seems to work fine for me based on this comment - https://github.com/computerjazz/react-native-draggable-flatlist/issues/422#issuecomment-1459073006

**Note: This also fixes the issue with nested virtualized lists mentioned in the other issue.**

- DO NOT USE NestableScrollContainer and NestableDraggableFlatList... see the issue I linked as to why
- Use a regular DraggableFlatList and supply the ListFooterComponent instead
- The trick is to use an empty array in your DraggableFlatList component, as seen below
    - Adding data to both places results in 2x the list entries
- Abandon all the used decorators; they blow up using this solution

I'm just going to paste my component here because I'm lazy...

`import React, {useCallback, useState} from 'react';
import {useDispatch, useSelector} from 'react-redux';
import {View, TouchableOpacity, FlatList} from 'react-native';
import {verticalScale} from 'react-native-size-matters';
import DraggableFlatList from 'react-native-draggable-flatlist';
import {PowerEntry} from '../../components/CharacterEdit/PowerEntry';
import {Button} from '../../components/Button/Button';
import {reorder} from '../../reducers/characterSlice';

const initializeData = powers => {
    return powers.map((power, i) => {
        return {
            key: `power-${i}`,
            label: power.label,
            power,
        };
    });
};

export const PowersTab = ({navigation, deletePower, toggleSrd}) => {
    const dispatch = useDispatch();

    const workingCharacter = useSelector(state => state.character.workingCharacter);

    const [scrollEnabled, setScrollEnabled] = useState(true);

    const renderItem = useCallback(
        ({item, drag}) => {
            return (
                <TouchableOpacity onLongPress={drag}>
                    <View style={{paddingTop: verticalScale(5)}}>
                        <PowerEntry
                            key={`power-${item.power.uuid}`}
                            navigation={navigation}
                            workingCharacter={workingCharacter}
                            power={item.power}
                            deletePower={deletePower}
                            toggleSrd={toggleSrd}
                        />
                    </View>
                </TouchableOpacity>
            );
        },
        [deletePower, navigation, toggleSrd, workingCharacter],
    );

    const keyExtractor = item => item.key;

    const powersData = initializeData(workingCharacter.powers);

    const renderFlatList = () => {
        return (
            <View>
                <FlatList data={powersData} renderItem={renderItem} keyExtractor={keyExtractor} />
            </View>
        );
    };

    const renderPowers = () => {
        if (workingCharacter.powers.length > 0) {
            return (
                <View style={{flex: 1, paddingTop: verticalScale(10)}}>
                    <DraggableFlatList
                        scrollEnabled={scrollEnabled}
                        data={[]}
                        onDragBegin={() => setScrollEnabled(false)}
                        onDragEnd={({from, to}) => {
                            setScrollEnabled(true);

                            dispatch(reorder({list: 'powers', from, to}));
                        }}
                        keyExtractor={keyExtractor}
                        renderItem={renderItem}
                        ListFooterComponent={renderFlatList}
                    />
                </View>
            );
        }

        return null;
    };

    return (
        <>
            <Button label="New" onPress={() => navigation.navigate('CharacterCreatePower')} />
            {renderPowers()}
        </>
    );
};
`

**Comment by leminhcse** [comment]
Hi, just downgrade Reanimated from 2.2.4 to 1.13.3 so the issue has been resolved !

**Comment by ausgandalf** [comment]
I switched to https://github.com/fivecar/react-native-draglist
