### ISSUE TITLE
Disable Rerender after Drag & Drop

### ISSUE THREAD

**Issue by iSaBo96** [computerjazz/react-native-draggable-flatlist#91]
Hallo everybody,

is there a posibility to disable the rerendering after i Drag & Drop an Item from the Flatlist?
Maybe it is a bug?

Thanks for your help

**Comment by hbarang** [comment]
What do you mean by rerender, does it happend twice when you drop?

Usually there is only one rerender at the Drop. Because it changes the state of your data in your flatlist, this should be the expected behaviour. However rerendering should not happen when you drag something unless you changed the behaviour.

If you think more than one render is called when you drop, can you add your code?

**Comment by thomasobrien99** [comment]
I experience this if I used LayoutAnimation.configureNext in a component within the list. For me, removing it was a workable solution.

**Comment by computerjazz** [comment]
Can you elaborate? Some rerendering is unavoidable -- for example when data/layouts change.
